feelings:
  study: 努力
  health: 健康
  appreciate: 感謝

categories:
  info: 'constant.info'
  study: 'constant.study'
  chat: 'constant.chat'
  
confirm_category:
  - bad

pri_options:
  record_pri: 日誌預設
  census_pri: 統計
  todo_pri: 目標
  friend_pri: 朋友

sealed:
  0: 公開
  1: 隱藏
  

admin_id: 2
