stage:
  adapter: mysql
  database: iwakela0_iwakela
  username: iwakela0_iwakela
  password: plokmiju1
  encoding: utf8

production:
  adapter: mysql
  database: iwakela0_iwakela
  username: root
  password: 0okm9ijn
  encoding: utf8

